#-------------------------------------------------------------------------------------------
# Copyright (c) 2022-2023, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[package]
name = "hyper_render"
version = "0.0.0"
edition = "2021"
license = "MIT"

[dependencies]
hyper_core = { path = "../hyper_core" }
hyper_math = { path = "../hyper_math" }
hyper_platform = { path = "../hyper_platform" }
hyper_vulkan = { path = "../hyper_vulkan" }

color-eyre = { version = "0.6", default-features = false }
log = "0.4"
