[package]
name = "hyper_rendering"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper_core = { path = "../hyper_core" }
hyper_platform = { path = "../hyper_platform" }

ash = "0.37.0"
gpu-allocator = "0.18.0"
log = "0.4.17"
nalgebra-glm = "0.17.0"
tobj = "3.2.3"
