#-------------------------------------------------------------------------------------------
# Copyright (c) 2022-2023 SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[package]
name = "hyper_editor"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
hyper_engine = { path = "crates/hyper_engine" }

chrono = { version = "0.4", default-features = false, features = [
    "alloc",
    "std",
    "clock",
] }
color-eyre = { version = "0.6", default-features = false }
fern = { version = "0.6", features = ["colored"] }
log = "0.4"

[workspace]
resolver = "2"
members = ["crates/*"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.profiling]
inherits = "release"
debug = true

[profile.production]
inherits = "release"
codegen-units = 1
strip = true
lto = true
