#-------------------------------------------------------------------------------------------
# Copyright (c) 2022-2023 SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[workspace]
resolver = "2"
members = [
    "hyper_core",
    "hyper_editor",
    "hyper_engine",
    "hyper_platform",
    "hyper_rendering",
]

[profile.dev]
opt-level = 1

[profile.profiling]
inherits = "release"
debug = true

[profile.production]
inherits = "release"
codegen-units = 1
strip = true
lto = true
