#-------------------------------------------------------------------------------------------
# Copyright (c) 2024, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[toolchain]
channel = "nightly"
components = ["rustc", "cargo", "rustfmt", "rust-std", "rust-docs", "clippy"]
