#-------------------------------------------------------------------------------------------
# Copyright (c) 2022-2023, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[package]
name = "hyper_platform"
version = "0.0.0"
edition = "2021"

[dependencies]
hyper_core = { path = "../hyper_core" }
hyper_math = { path = "../hyper_math" }

log = { workspace = true }
raw-window-handle = { workspace = true }
thiserror = { workspace = true }
winit = { workspace = true }
