#-------------------------------------------------------------------------------------------
# Copyright (c) 2022-2023, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[package]
name = "hyper_platform"
version = "0.0.0"
edition = "2021"

[dependencies]
hyper_core = { path = "../hyper_core" }
hyper_math = { path = "../hyper_math" }

log = "0.4"
raw-window-handle = "0.6"
thiserror = "1.0"
winit = "0.30"
