[package]
name = "hyper_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper_engine = { path = "../hyper_engine" }

color-eyre = "0.6.2"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
tracing-tracy = "0.10.0"
