#-------------------------------------------------------------------------------------------
# Copyright (c) 2023-2024, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[package]
name = "hyper_math"
version = "0.0.0"
edition = "2021"

[dependencies]
hyper_core = { path = "../hyper_core" }

glam = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
