#-------------------------------------------------------------------------------------------
# Copyright (c) 2023, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[package]
name = "hyper_editor"
version = "0.0.0"
edition = "2021"
license = "MIT"

[dependencies]
hyper_engine = { path = "../hyper_engine" }

anyhow = "1.0"
chrono = { version = "0.4", default-features = false, features = [
    "alloc",
    "std",
    "clock",
] }
fern = { version = "0.6", features = ["colored"] }
log = "0.4"
