#-------------------------------------------------------------------------------------------
# Copyright (c) 2023, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[package]
name = "hyper_vulkan"
version = "0.0.0"
edition = "2021"
license = "MIT"

[dependencies]
hyper_core = { path = "../hyper_core" }
hyper_math = { path = "../hyper_math" }
hyper_platform = { path = "../hyper_platform" }

ash = { git = "https://github.com/ash-rs/ash.git" }
ash-window = { git = "https://github.com/ash-rs/ash.git" }
bitflags = "2.4"
color-eyre = { version = "0.6", default-features = false }
gpu-allocator = { git = "https://github.com/SkillerRaptor/gpu-allocator.git" }
log = "0.4"
raw-window-handle = "0.5"
