#-------------------------------------------------------------------------------------------
# Copyright (c) 2022-2023 SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[package]
name = "hyper_vulkan"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
hyper_core = { path = "../hyper_core" }
hyper_platform = { path = "../hyper_platform" }

ash = "0.37"
ash-window = "0.12"
color-eyre = { version = "0.6", default-features = false }
log = "0.4"
nalgebra-glm = "0.18"
raw-window-handle = "0.5"
vma = "0.3"
