#-------------------------------------------------------------------------------------------
# Copyright (c) 2022-2023 SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[package]
name = "hyper_platform"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
hyper_core = { path = "../hyper_core" }

color-eyre = { version = "0.6", default-features = false }
log = "0.4"
nalgebra-glm = "0.18"
raw-window-handle = "0.5"
winit = { version = "0.29", default-features = false, features = [
    "rwh_05",
    "x11",
] }
