#-------------------------------------------------------------------------------------------
# Copyright (c) 2022-2024, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[package]
name = "hyper_core"
version = "0.0.0"
edition = "2021"

[dependencies]
hyper_core_macros = { path = "./macros" }

thiserror = { workspace = true }
tracing = { workspace = true }
