#-------------------------------------------------------------------------------------------
# Copyright (c) 2022-2024, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[package]
name = "hyper_core"
version = "0.0.0"
edition = "2021"
license = "MIT"

[dependencies]
hyper_core_macros = { path = "./macros" }

log = "0.4"
thiserror = "1.0"
