#-------------------------------------------------------------------------------------------
# Copyright (c) 2024, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[package]
name = "hyper_rhi"
version = "0.0.0"
edition = "2021"

[dependencies]
hyper_core = { path = "../hyper_core" }
hyper_math = { path = "../hyper_math" }
hyper_platform = { path = "../hyper_platform" }

ash = { workspace = true }
ash-window = { workspace = true }
hassle-rs = { workspace = true }
gpu-allocator = { workspace = true }
raw-window-handle = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true }
