#-------------------------------------------------------------------------------------------
# Copyright (c) 2024, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[package]
name = "hyper_rhi"
version = "0.0.0"
edition = "2021"

[dependencies]
hyper_core = { path = "../hyper_core" }
hyper_math = { path = "../hyper_math" }
hyper_platform = { path = "../hyper_platform" }

ash = { git = "https://github.com/SkillerRaptor/ash" }
ash-window = { git = "https://github.com/SkillerRaptor/ash" }
hassle-rs = "0.11"
gpu-allocator = { git = "https://github.com/Traverse-Research/gpu-allocator.git" }
log = "0.4"
raw-window-handle = "0.6"
thiserror = "1.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Security",
    "Win32_System_Threading",
] }
