#-------------------------------------------------------------------------------------------
# Copyright (c) 2022-2024, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[package]
name = "hyper_rhi"
version = "0.0.0"
edition = "2021"
license = "MIT"

[dependencies]
hyper_core = { path = "../hyper_core" }
hyper_math = { path = "../hyper_math" }
hyper_platform = { path = "../hyper_platform" }

ash = "0.38"
ash-window = "0.13"
hassle-rs = "0.11"
gpu-allocator = { git = "https://github.com/Traverse-Research/gpu-allocator.git", branch = "ash-0.38" }
log = "0.4"
thiserror = "1.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.56", features = [
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Security",
    "Win32_System_Threading",
] }
