name: build-windows

on: [ push, pull_request ]

jobs:
  build-windows:
    runs-on: windows-2022
    defaults:
      run:
        shell: cmd
    env:
      vulkan_sdk: "${{ github.workspace }}/vulkan_sdk/"
      vulkan_version: "1.2.189.0"
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows MSVC Debug",
            artifact: "windows-msvc-debug.zip",
            cc: "cl",
            cxx: "cl",
            cmake_build_options: "--config Debug",
            cmake_configure_options: '-G "Visual Studio 17 2022" -A x64 -T host=x64',
            build_type: "Debug"
          }
          - {
            name: "Windows MSVC Release",
            artifact: "windows-msvc-release.zip",
            cc: "cl",
            cxx: "cl",
            cmake_build_options: "--config Release",
            cmake_configure_options: '-G "Visual Studio 17 2022" -A x64 -T host=x64',
            build_type: "Release"
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Vulkan SDK
        run: |
          curl -LS -o vulkansdk.exe https://sdk.lunarg.com/sdk/download/${{ env.vulkan_version }}/windows/VulkanSDK-${{ env.vulkan_version }}-Installer.exe?Human=true
          7z x vulkansdk.exe -o"${{ env.vulkan_sdk }}"

      - name: Configure CMake
        run: |
          set CC=${{ matrix.config.cc }}
          set CXX=${{ matrix.config.cxx }}
          set PATH=%PATH%;${{ env.vulkan_sdk }}\;${{ env.vulkan_sdk }}\Bin\

          cmake . -B build -D CMAKE_BUILD_TYPE=${{ matrix.config.build_type }}

      - name: Build
        run: |
          cmake --build build ${{ matrix.config.cmake_build_options }}

      - name: Test
        run: |
          cd build
          ctest -C ${{ matrix.config.build_type }}

      - name: Prepare upload
        run: |
          7z a -tzip ${{ matrix.config.artifact }} build/*

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          path: ${{ matrix.config.artifact }}
          name: ${{ matrix.config.artifact }}
