name: Cargo Build & Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: HyperEngine
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build
        run: |
          cargo build --verbose

      - name: Test
        run: |
          cargo test --verbose

