name: Cargo Build & Test

on: [push, pull_request]

jobs:
  build:
    name: HyperEngine
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - nightly
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update System
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update -qq
          sudo apt install -y \
            libxinerama-dev \
            libxkbcommon-dev \
            xorg-dev  \

      - name: Install Rust-Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustc, cargo, rustfmt, rust-std, rust-docs, clippy, miri

      - name: Install Cargo-Nextest
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-nextest
          locked: true

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: true
          cache-on-failure: true
          cache-all-crates: true

      - name: Cargo Build Debug
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --workspace

      - name: Cargo Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --workspace --release

      - name: Cargo Build Production
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --workspace --profile production

      - name: Cargo Build Profiling
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --workspace --profile profiling

      - name: Cargo Formatter
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Cargo Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets

      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run
