name: Cargo Build & Test

on: [push, pull_request]

jobs:
  build:
    name: HyperEngine
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - debug
          - release
        toolchain:
          - stable
          - beta
          - nightly
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update System
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update -qq
          sudo apt install -y \
            cmake \
            extra-cmake-modules \
            libwayland-dev \
            libxinerama-dev \
            libxkbcommon-dev \
            wayland-protocols \
            xorg-dev  \

      - name: Update
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Debug
        if: matrix.config == 'debug'
        run: |
          cargo build --verbose --workspace

      - name: Build Release
        if: matrix.config == 'release'
        run: |
          cargo build --verbose --workspace --release

      - name: Test
        run: |
          cargo test --verbose --workspace

