name: Cargo Build & Test

on: [push, pull_request]

jobs:
  build:
    name: HyperEngine
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - nightly
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust-Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustc, cargo, rustfmt, rust-std, rust-docs, clippy, miri

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: true
          cache-on-failure: true
          cache-all-crates: true

      - name: Cargo Build Debug
        run: cargo build --workspace --verbose

      - name: Cargo Build Release
        run: cargo build --workspace --release --verbose

      - name: Cargo Build Production
        run: cargo build --workspace --profile production --verbose

      - name: Cargo Build Profiling
        run: cargo build --workspace --profile profiling --verbose

      - name: Cargo Formatter
        run: cargo fmt --all -- --check --verbose

      - name: Cargo Check
        run: cargo check --all-targets --verbose

      - name: Cargo Test
        run: cargo test --verbose
