#-------------------------------------------------------------------------------------------
# Copyright (c) 2024, SkillerRaptor
#
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------------------

[package]
name = "hyper_engine"
version = "0.0.0"
edition = "2021"

[dependencies]
hyper_core = { path = "../hyper_core" }
hyper_ecs = { path = "../hyper_ecs" }
hyper_math = { path = "../hyper_math" }
hyper_platform = { path = "../hyper_platform" }
hyper_rhi = { path = "../hyper_rhi" }

log = { workspace = true }
thiserror = { workspace = true }
